export const GET_POSTS = "GET_POSTS";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const DELETE_SUCCESS = "DELETE_SUCCESS";
